version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: odo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odo_user
      POSTGRES_PASSWORD: P@ssword!
      POSTGRES_DB: odo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
